In [1]:
# 학습 데이터 생성

import torch

x_train = torch.FloatTensor([ [1,2,1,1], [2,1,3,2], [3,1,3,4], [4,1,5,5], [1,7,5,5], [1,2,5,6], [1,6,6,6], [1,7,7,7] ])
y_train = torch.FloatTensor([ [0,0,1], [0,0,1], [0,0,1], [0,1,0], [0,1,0], [0,1,0], [1,0,0], [1,0,0] ])

In [6]:
W = torch.zeros(4, 3, requires_grad=True)
b = torch.zeros(1, 3, requires_grad=True)
optimizer = torch.optim.Adam([W,b], lr=0.1)

In [8]:
for epoch in range(3001):
  hypothesis = torch.softmax(torch.mm(x_train, W)+b, dim=1)
  cost = -torch.mean(torch.sum(y_train * torch.log(hypothesis), dim=1))
  
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 300 == 0:
    print("epoch: {}, cost: {:.6f}".format(epoch, cost.item()))

epoch: 0, cost: 1.098612
epoch: 300, cost: 0.105263
epoch: 600, cost: 0.042634
epoch: 900, cost: 0.023111
epoch: 1200, cost: 0.014479
epoch: 1500, cost: 0.009879
epoch: 1800, cost: 0.007124
epoch: 2100, cost: 0.005338
epoch: 2400, cost: 0.004113
epoch: 2700, cost: 0.003236
epoch: 3000, cost: 0.002588


In [9]:
W.requires_grad_(False)
b.requires_grad_(False)

x_test = torch.FloatTensor([[1,11,10,9], [1,3,4,3], [1,1,0,1]])
test_all = torch.softmax(torch.mm(x_test, W)+b, dim=1) 
print(test_all)
print(torch.argmax(test_all, dim=1))

tensor([[1.0000e+00, 5.5164e-19, 7.0150e-38],
        [1.4800e-02, 7.4294e-01, 2.4226e-01],
        [1.2256e-33, 9.0835e-12, 1.0000e+00]])
tensor([0, 1, 2])


In [10]:
# 더 심플하게 구현해보기!

In [29]:
# 학습 데이터 생성

import torch
import torch.nn.functional as F

x_train = torch.FloatTensor([ [1,2,1,1], [2,1,3,2], [3,1,3,4], [4,1,5,5], [1,7,5,5], [1,2,5,6], [1,6,6,6], [1,7,7,7] ])
y_train = torch.LongTensor([2,2,2,1,1,1,0,0])

In [30]:
W = torch.zeros(4, 3, requires_grad=True)
b = torch.zeros(1, 3, requires_grad=True)
optimizer = torch.optim.Adam([W,b], lr=0.1)

In [31]:
import torch.nn as nn

model = nn.Linear(4, 3)
# weight 를 xavier uniform 으로 normalization.
torch.nn.init.xavier_uniform_(model.weight)
optimizer = torch.optim.Adam(model.parameters(), lr=1)

for epoch in range(3001):
  z = model(x_train)
  c = F.cross_entropy(z, y_train)

  optimizer.zero_grad()
  c.backward()
  optimizer.step()

  if epoch % 300 == 0:
    print("epoch: {}, cost: {:.6f}".format(epoch, c.item()))

epoch: 0, cost: 1.806755
epoch: 300, cost: 0.023668
epoch: 600, cost: 0.009067
epoch: 900, cost: 0.004854
epoch: 1200, cost: 0.003035
epoch: 1500, cost: 0.002072
epoch: 1800, cost: 0.001496
epoch: 2100, cost: 0.001123
epoch: 2400, cost: 0.000866
epoch: 2700, cost: 0.000682
epoch: 3000, cost: 0.000546


In [33]:
x_test = torch.FloatTensor([[1,11,10,9], [1,3,4,3], [1,1,0,1]])
model(x_test).argmax(dim=1)

tensor([0, 1, 2])